// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
  traceId: string;
  DB_TYPE: string;
  DBC: string;
  KV: KVNamespace;
  ASSETS: Fetcher;
}
