#:schema node_modules/wrangler/config-schema.json
name = "vanguard"
main = "src/index.ts"
compatibility_date = "2024-11-25"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./public/", binding = "ASSETS" }

[observability]
enabled = true

[vars]
DB_TYPE = "KV"
DBC = "Vanguard"

[[kv_namespaces]]
binding = "KV"
id = "vanguard"
